### ISSUE TITLE
aloussase/scout repo disappeared ?

### ISSUE THREAD

**Issue by teto** [mrcjkb/haskell-tools.nvim#106]
### Question

The readme links to https://github.com/aloussase/scout but the repo disappeared (which broke my neovim plugins update). Any idea why ?

**Comment by mrcjkb** [comment]
It looks like the owner has deleted it or made it private.
@aloussase have there been any issues with it?

I have forked it, because I wanted to package it with nix, but hadn't gotten around to it yet: https://github.com/mrcjkb/scout-fork

For now, I will remove it from the readme.
