### ISSUE TITLE
How to specify how a codelens is displayed

### ISSUE THREAD

**Issue by MangoIV** [mrcjkb/haskell-tools.nvim#126]
### Question

Codelenses are displayed directly after some code with no space and in the same color that the code is written in. I would like them to be displayed in a different colour and perhaps with a separator, similarly to how I can style diagnostics. 

Thanks in advance.

**Comment by mrcjkb** [comment]
For the colour, you can set the `LspCodeLens` highlight group (see #29).

If you use a theme plugin, I recommend opening an issue or a PR for that theme (see for example https://github.com/marko-cerovac/material.nvim/pull/144).

You can define a `LspCodeLensSeparator` highlight group for separators between two or more code lenses.
But afaik, there's currently no way to define a separator between the buffer text and the code lens's virtual text, like there is for diagnostics. Neovim doesn't have a `vim.lsp.codelens.config` equivalent of `vim.diagnostic.config`. You would have to override the `vim.lsp.codelens.display` function.

**Comment by MangoIV** [comment]
Thank you for the answer!

**Comment by mrcjkb** [comment]
I just added a codeLens [override to my personal config](https://github.com/mrcjkb/nvim-config/blob/master/lua/mrcjk/lsp.lua#L28) that adds an icon to separate it from the regular text.
