### ISSUE TITLE
Where should binaries be installed with Nix?

### ISSUE THREAD

**Issue by collinarnett** [mrcjkb/haskell-tools.nvim#145]
### Question

I'm trying to figure out where the best place is to include haskell-language-server when it comes to scope in NixOS. Should I couple hls in my flake based project directory and include haskell-tools in my global configuration? Or should I try and keep haskell-tools with my project? 

My current neovim configuration is here:
https://github.com/collinarnett/brew/blob/main/modules/home-manager/neovim/neovim.nix

For scala, I keep my lsp server embedded in my project where my configuration for said lsp server stays in my global neovim configuration.

I'm sorta new to haskell and I don't have complex project with cabal and stack configurations but I would like to leverage auto-completion and error detection so I'm just a bit confused on where I should put things.

**Comment by mrcjkb** [comment]
I personally do both. I add `haskell-language-server` to my system packages with my Neovim module so that I can contribute to non-nix Haskell projects that I don't own myself.
In nix-based Haskell projects, I enter a nix shell in which `hls` is typically included.

**Comment by teto** [comment]
I have an alias `nhs94` that will give me a shell with hls 9.4 as a backup for random projects but my philosophy is to have it per-project (which fits nix's philosophy better IMO)
