### ISSUE TITLE
[MISC] Note of Gratitude

### ISSUE THREAD

**Issue by TheCedarPrince** [mrcjkb/haskell-tools.nvim#160]
Hi @mrcjkb ,

I didn't know how to reach you but just wanted to write a quick thank you note for making this suite of Haskell tools for neovim. I've been experimenting with Haskell in the past before these tools existed. Very excited to get back onto Haskell dev using your tools -- they are super nice!

Thanks!

tcp :deciduous_tree:

P.S. Feel free to close this issue! :smile:

**Comment by mrcjkb** [comment]
Thanks for the nice words! This made my day!
