### ISSUE TITLE
Allow setting hls `cmd` per project

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/haskell-tools.nvim#200]
### Feature description

This would be useful e.g. to set `cmd = cabal run haskell-language-server -- --lsp` in the hls project.

**Comment by glyh** [comment]
It should also be good if this plugin can detect the haskell-language-server version we should use. I have haskell-language-server in my path but it's complaining that the version of ghcide doesn't match my package. 

I search here and got https://www.reddit.com/r/haskell/comments/i8rfx0/ghcide_compiled_against_ghc_865_but_currently/

But I have no clue how to fix the issue.

**Comment by glyh** [comment]
Hello, I'm using ghcup with stack 2.9.3, hls 2.0.0.1, ghc 9.2.8 and cabal 3.6.2. But I am still getting the errors.

**Comment by mrcjkb** [comment]
If you're using ghcup with stack, you may need to [configure stack to use the `ghc` binaries managed by ghcup](https://www.haskell.org/ghcup/guide/#stack-integration).

See also [vscode-haskell#ghc-abis-dont-match](https://github.com/haskell/vscode-haskell#ghc-abis-dont-match).

As installing haskell-language-server is beyond the scope of this plugin, I suggest you ask on [IRC](https://web.libera.chat/?channels=#haskell-language-server), in the [haskell tooling matrix channel](https://matrix.to/#/#haskell-tooling:matrix.org), or open [an issue](https://github.com/haskell/haskell-language-server/issues) in the haskell-language-server repository if you're still facing issues.

Arch's [static Haskell packages (in the AUR)](https://aur.archlinux.org/packages/haskell-language-server-static) don't seem to be broken. But they may have the same issue with stack.

**Comment by anuramat** [comment]
ghcup on NixOS is a PITA: the package is broken for half a year, and binaries from the website have a dynamic loader, so in my opinion this option could be pretty useful

**Comment by mrcjkb** [comment]
This has been supported for a while - I just forgot about the issue :smile:

With the current version of this plugin, there are multiple ways you can dynamically set the `cmd`:

1. Using [`:h exrc`](https://neovim.io/doc/user/options.html#'exrc'): 
  If enabled, you can set `vim.g.haskell_tools` in `.nvim.lua`, `.nvimrc`, or `.exrc` files in the project root.
1. Since version 2.4.0, `vim.g.haskell_tools` can also be a function. So you can use that to determine the project you're in and return a value accordingly.
1. `vim.g.haskell_tools.hls.cmd` can also be either a list of strings or a function that returns a list of strings.

The first two methods won't work if you load multiple projects with the same Neovim session, as `vim.g.haskell_tools` is sourced into an internal config only once, when opening a Haskell file.

If `hls.cmd` is a function, it is evaluated every time the LSP client starts, so this method can be used with multiple projects in the same session.

**Comment by mrcjkb** [comment]
> ghcup on NixOS is a PITA: the package is broken for half a year, and binaries from the website have a dynamic loader, so in my opinion this option could be pretty useful (the executable override)

If you only need to override the `cmd`, that has always been supported. See `:h haskell-tools.config` and `:h HaskellLspClientOpts`.

**Comment by anuramat** [comment]
damn, how did I miss that
I swear I Read TFM
thanks for the help 🙇‍♂️
