### ISSUE TITLE
virtual type signatures show ^@ instead of line break

### ISSUE THREAD

**Issue by mauke** [mrcjkb/haskell-tools.nvim#208]
### Neovim version (nvim -v)

v0.9.1

### Operating system/version

CentOS 7.9

### Output of `haskell-language-server-wrapper --version`

1.10.0.0 (GHC: 8.10.7)

### How to reproduce the issue

Put code in Haskell file (like `example.hs`):
```haskell
example f _ = (fmap . fmap . fmap) f
```

### Expected behaviour

Type signature is shown as virtual text:
```haskell
example :: (Functor f1, Functor f2, Functor f3) => (a -> b) -> p -> f1 (f2 (f3 a)) -> f1 (f2 (f3 b))
```

### Actual behaviour

Type signature is shown, but has `=>^@` in the middle:
```haskell
example :: (Functor f1, Functor f2, Functor f3) =>^@(a -> b) -> p -> f1 (f2 (f3 a)) -> f1 (f2 (f3 b))
```

### The minimal config used to reproduce this issue.

I don't know what this is.

**Comment by mrcjkb** [comment]
To rule out that this is a [haskell-language-server](https://github.com/haskell/haskell-language-server) issue:

- Does it occur with older versions? (0.9.x)
- Does it occur with the latest version? (2.0.0)

I haven't been able to reproduce this with either of the two versions on NixOS (I'd have to try 1.10.0 later).

It could also be a Neovim issue?
You could check what text is coming from haskell-language-server by overriding the LSP codeLens handler as follows:

```lua
local default_on_codelens = vim.lsp.codelens.on_codelens
vim.lsp.codelens.on_codelens = function(err, lenses, ctx, _)
  if err or not lenses or not next(lenses) then
    return default_on_codelens(err, lenses, ctx, _)
 end
 for _, lens in pairs(lenses) do
   if lens and lens.command and lens.command.title then
     lens.command.title = vim.print(lens.command.title)
   end
 end
 return default_on_codelens(err, lenses, ctx, _)
end
```

This will print out every code lens title (which is what Neovim displays as virtual text).

**Comment by mauke** [comment]
I can reproduce it with haskell-language-server 2.0.0.0, 2.0.0.1, 1.9.1.0, 1.8.0.0.

With the custom handler I see only `(a -> b) -> p -> f1 (f2 (f3 a)) -> f1 (f2 (f3 b))` in the bottom line, but `:messages` shows:
```
example :: (Functor f1, Functor f2, Functor f3) =>
(a -> b) -> p -> f1 (f2 (f3 a)) -> f1 (f2 (f3 b))
```
... which is consistent with `lens.command.title` containing a newline.

And indeed, using
```lua
    lens.command.title = vim.print(string.gsub(lens.command.title, "\n", " "))
```
fixes it.

**Comment by mrcjkb** [comment]
Ah. In this case, I would say it's a neovim issue.

Thanks for the troubleshooting.
