### ISSUE TITLE
Inline type hints don't show up after update to 1.11.2

### ISSUE THREAD

**Issue by kamoshi** [mrcjkb/haskell-tools.nvim#229]
### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Arch Linux

### Output of `haskell-language-server-wrapper --version`

haskell-language-server version: 2.0.0.1 (GHC: 8.10.7) (PATH: /home/kamov/.ghcup/hls/2.0.0.1/lib/haskell-language-server-2.0.0.1/bin/haskell-language-server-wrapper)

### How to reproduce the issue

Update `haskell-tools` from `1.11.1` to `1.11.2`
```
Updated (1)
    ○ haskell-tools.nvim   haskell
        369d81b docs(changelog): release notes (2 days ago)
        a589a80 fix(cabal): prevent error messages caused by external lsp plugins (#224) (2 days ago)
        d38c1b6 style(readme): sloth heading -> paragraph (3 days ago)
        53014f4 fix: hotfix for neovim-nightly compatibility update (3 days ago)
        ca6972d chore: neovim-nightly compatibility update (#222) (3 days ago)
        ff7dad6 chore: use lua-ls from pre-commit-hooks-nix + add type cast (3 days ago)
        070f78d chore: update flake.lock (#220) (13 days ago)
        9bc5409 ci: replace typecheck with lua-ls pre-commit-hook (#219) (3 weeks ago)
```

### Expected behaviour

![image](https://github.com/mrcjkb/haskell-tools.nvim/assets/18511281/9221c7d9-8068-41f9-8f4b-5c0e9cea828a)

### Actual behaviour

![image](https://github.com/mrcjkb/haskell-tools.nvim/assets/18511281/374fc519-6a38-4e8d-803d-6dbd4a1f7021)

### The minimal config used to reproduce this issue.

I use the `Lazy` package manager and the default config in `ftplugin/haskell.lua` as shown in the README of this project

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)


require("lazy").setup({
  {
    'mrcjkb/haskell-tools.nvim',
    dependencies = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope.nvim',
    },
    version = '1.11.2', -- use 1.11.1 to see inline hints working correctly
  }
})
```

**Comment by mrcjkb** [comment]
Thanks for reporting this.
I have been able to reproduce it with your config and will investigate.
Strangely, this does not affect the `2.x.x` branch anymore.

**Comment by mrcjkb** [comment]
@all-contributors Please add @kamoshi for bug.

**Comment by mrcjkb** [comment]
@all-contributors Please add @kamoshi for bug.

**Comment by mrcjkb** [comment]
@all-contributors please add @kamoshi for bug.

**Comment by mrcjkb** [comment]
@all-contributors Please add @kamoshi for bug.

**Comment by mrcjkb** [comment]
@all-contributors Please add @kamoshi for bug.

**Comment by mrcjkb** [comment]
Fixed. Thanks for the detailed report @kamoshi :smile:
