### ISSUE TITLE
Try both haskell-language-server-wrapper and haskell-language-server by default

### ISSUE THREAD

**Issue by purefn** [mrcjkb/haskell-tools.nvim#233]
### Feature description

I'm using haskell.nix and its `shellFor` to supply HLS. haskell.nix does not provide the wrapper script, https://github.com/input-output-hk/haskell.nix/issues/1776, just the exe. If there isn't a wrapper available, we should check to see if we can find a haskell-language-server exe on the path.

**Comment by mrcjkb** [comment]
Hi. Thanks for the suggestion.
I'll add that to the upcoming `2.0.0` release.
