### ISSUE TITLE
Missing many syntax highlights (LazyVim)

### ISSUE THREAD

**Issue by seanhess** [mrcjkb/haskell-tools.nvim#234]
### Neovim version (nvim -v)

v0.9.1

### Operating system/version

OSX 13.4.1 Ventura

### Output of `haskell-language-server-wrapper --version`

haskell-language-server version: 2.0.0.1 (GHC: 8.10.7)

### How to reproduce the issue

1. Install LazyVim https://www.lazyvim.org/installation
2. Add `return { "mrcjkb/haskell-tools.nvim" }` to ~/.config/nvim/lua/plugins/haskell.lua
3. Finish [installation instructions](https://github.com/mrcjkb/haskell-tools.nvim#quick-setup) (ftplugin/haskell.lua)
4. Open a Haskell file

### Expected behaviour

Colored highlighting of `IO` and other types in function signatures, matching the screenshots in the README. 

### Actual behaviour

Only minimal highlighting, as if the plugin weren't loaded.

It's definitely loaded though: I'm getting the 2.0.0 warning and HSL errors. 

<img width="336" alt="Screenshot 2023-08-08 at 4 01 06 PM" src="https://github.com/mrcjkb/haskell-tools.nvim/assets/16249/293bc1b3-6523-4924-bb50-f5b92583bd42">

<img width="408" alt="Screenshot 2023-08-08 at 4 05 45 PM" src="https://github.com/mrcjkb/haskell-tools.nvim/assets/16249/313947f1-cbb5-4745-a759-4653616a0552">

<img width="701" alt="Screenshot 2023-08-08 at 4 07 52 PM" src="https://github.com/mrcjkb/haskell-tools.nvim/assets/16249/30a1455e-611f-4a53-a4ad-074b9931bfa1">

### The minimal config used to reproduce this issue.

See how to reproduce above

**Comment by mrcjkb** [comment]
This plugin doesn't implement syntax highlighting.

For that, I recommend [`treesitter-nvim`](https://github.com/nvim-treesitter/nvim-treesitter). You will need to [ensure the tree-sitter parser for Haskell is installed].(https://github.com/nvim-treesitter/nvim-treesitter#language-parsers)

**Comment by mrcjkb** [comment]
It looks like you're using LazyVim?

If so, see this page: https://www.lazyvim.org/plugins/treesitter

**Comment by seanhess** [comment]
I see, the step I was missing was:

```
:TSInstall haskell
```

Still new to neovim and treesitter, I didn't realize there was a separate install step for each language. Thanks!

**Comment by mrcjkb** [comment]
You can also add `ensure_installed = { 'haskell', }` (and whatever other languages) or even `ensure_installed = 'all'` to the `treesitter-nvim` plugin configuration.
Then it'll install whatever parsers are missing automatically 😄

**Comment by seanhess** [comment]
Ah that's exactly what I was looking for! And.... now I see it in comments for plugins.lua in lazyvim. Thanks for your help!
