### ISSUE TITLE
how can I change warnings/errors not to report inline but on hover?

### ISSUE THREAD

**Issue by MaciekFlis** [mrcjkb/haskell-tools.nvim#236]
### Question

I don't want my warnings or errors to show inline, I'm never able to read full text.

![reported_warning](https://github.com/mrcjkb/haskell-tools.nvim/assets/19313722/485a305c-16e4-4048-b04e-76d866210dc8)

how can I make it display in a hover window, like in this gif in readme:

![docu_gif](https://user-images.githubusercontent.com/12857160/219751911-f45e4131-afad-47b3-b016-1d341c71c114.gif)

**Comment by mrcjkb** [comment]
Check out the [`vim.diagnostic` API](https://neovim.io/doc/user/diagnostic.html) (`:h diagnotic` in neovim).

For floating windows, you want [`vim.diagnostic.open_float()`](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.open_float()), and possibly `goto_prev` and `goto_next` to navigate them.

Personally, I have the following keymaps:

```lua
local diagnostic= vim.diagnostic
local keymap = vim.keymap
local severity = diagnostic.severity

local opts = { noremap = true, silent = true }
keymap.set('n', '<space>e', function()
  local _, winid = diagnostic.open_float(nil, { scope = 'line' })
  vim.api.nvim_win_set_config(winid or 0, { focusable = true })
end, opts)
keymap.set('n', '[d', diagnostic.goto_prev, opts)
keymap.set('n', ']d', diagnostic.goto_next, opts)
keymap.set('n', '[e', function()
  diagnostic.goto_prev {
    severity = severity.ERROR,
  }
end, opts)
keymap.set('n', ']e', function()
  diagnostic.goto_next {
    severity = severity.ERROR,
  }
end, opts)
keymap.set('n', '[w', function()
  diagnostic.goto_prev {
    severity = severity.WARN,
  }
end, opts)
keymap.set('n', ']w', function()
  diagnostic.goto_next {
    severity = severity.WARN,
  }
end, opts)
keymap.set('n', '[h', function()
  diagnostic.goto_prev {
    severity = severity.HINT,
  }
end, opts)
keymap.set('n', ']h', function()
  diagnostic.goto_next {
    severity = severity.HINT,
  }
end, opts)
```

You may also want to check out [this plugin](https://sr.ht/~whynothugo/lsp_lines.nvim/).

**Comment by MaciekFlis** [comment]
this is exactly what I needed, thank you!
do you know how to hide the current inline diagnostic?

**Comment by mrcjkb** [comment]
Thanks for the donation ☺️

Yes, you can disable them with

```lua
vim.diagnostic.config({
  virtual_text = false,
})
```

**Comment by mrcjkb** [comment]
@all-contributors please add @MaciekFlis for financial

**Comment by MaciekFlis** [comment]
works like a charm, thank you
