### ISSUE TITLE
Make Hoogle independent of LSP

### ISSUE THREAD

**Issue by SeungheonOh** [MrcJkb/haskell-tools.nvim#24]
I really like Hoogle integration, but I'd be very nice to use it without having LSP dependency. Perhaps, can you pull of the Hoogle part and make a separate project?

**Comment by MrcJkb** [comment]
For live Hoogle search without the LSP dependency, I recommend this plugin: https://github.com/luc-tielen/telescope_hoogle.

(On which much of the hoogle integration of my plugin is based).

**Comment by SeungheonOh** [comment]
Great. I'll check that out. Thank you
