### ISSUE TITLE
Idea: underscore code action that queries Hoogle

### ISSUE THREAD

**Issue by ners** [MrcJkb/haskell-tools.nvim#25]
If I write an expression such as:

getLine >>= _

and trigger a code action on _, it could give suggestions for `String -> IO a`

**Comment by MrcJkb** [comment]
Not a code action, but [this does the trick](https://github.com/MrcJkb/haskell-tools.nvim/tree/25-hoogle-fill-holes#use-hoogle-search-to-fill-holes).
