### ISSUE TITLE
dont know if its a bug but code actions to eta reduce doesnt work

### ISSUE THREAD

**Issue by SerjoA** [mrcjkb/haskell-tools.nvim#260]
### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Mac OS ventura

### Output of `:checkhealth haskell-tools`

all is good 

### How to reproduce the issue

first thank you for a wonderfull plugin, great job :)
attached some pictures
<img width="1279" alt="CleanShot 2023-09-22 at 00 06 31@2x" src="https://github.com/mrcjkb/haskell-tools.nvim/assets/4338000/726bdae3-6b62-4308-a859-f6499edd8f8d">
<img width="710" alt="CleanShot 2023-09-22 at 00 06 37@2x" src="https://github.com/mrcjkb/haskell-tools.nvim/assets/4338000/b402d1cb-7758-423f-aee4-56785f96ce75">

### Expected behaviour

i excpect the code action to be able to do eta reduction 

### Actual behaviour

only works for imports 

### The minimal config used to reproduce this issue.

dont know what config to use, i use the default you have in the readme

**Comment by mrcjkb** [comment]
Hey @SerjoA 👋
Thanks for the nice words 😃

Based on the screenshot it looks like you're calling `vim.lsp.codeLens.run()`.
For code actions, you want `vim.lsp.buf.code_action()`

**Comment by SerjoA** [comment]
thank you it did solve my problem once i changed keymap to code action
