### ISSUE TITLE
feat request: add ft field in lsp spec

### ISSUE THREAD

**Issue by xiaoshihou514** [mrcjkb/haskell-tools.nvim#275]
### Feature description

Thanks for this great one-stop solution for setting up Haskell dev environment! 
This feature request is here because I have sth in my status line that checks if the attached lsp's filetype contains the current buffer's ft. It would be very nice if `haskell-tools.nvim` provide these so that other plugins/scripts can identify `haskell-tools.nvim` as a Haskell lsp.

```lua
vim.print(vim.lsp.get_active_clients()[1].config.filetype)                                                         
-- Expected: {"haskell", "cabal" ...}
-- Actual: nil
```

**Comment by mrcjkb** [comment]
Hey 👋 

Sure, that shouldn't be hard to implement. I'll look into it later today 😊

**Comment by xiaoshihou514** [comment]
Thank you!
