### ISSUE TITLE
new entries removed on write in cabal files

### ISSUE THREAD

**Issue by waalge** [mrcjkb/haskell-tools.nvim#282]
### Neovim version (nvim -v)

v0.9.2

### Operating system/version

NixOS 23.11.20230925.6500b45

### Output of `:checkhealth haskell-tools`

Ok

### How to reproduce the issue

Open cabal file. Add new exposed module. Write file 

### Expected behaviour

New entry remains

### Actual behaviour

New entry is removed

### The minimal config used to reproduce this issue.

Using lazy, no config beyond the default.

**Comment by waalge** [comment]
To add some context. I've just switched back to nvim after using helix for a while. Wanting something more opinionated I am using Lazyvim with pretty much the plugins in the example + a few extras including this one. 

Its possible this behaviour is coming from some other plugin, although I think that would be odd. But I also think its odd that if it is coming from haskell-tools, that I can't see another issue reporting it.

If I edit the file in, say, helix and open in nvim then on write does not undo the change.

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for reporting.
I provide a minimal config that uses lazy.nvim. See `troubleshooting/minimal.lua` in this repo (no other plugins installed).

Are you able to reproduce the behaviour with that?
If not, you can use that as a basis for figuring out if it's another plugin, by gradually adding more plugins.

**Comment by waalge** [comment]
Cheers for that. 

No - I cannot reproduce it with a the minimal setup. Potentially some magic interplay bewteen plugins.

**Comment by mrcjkb** [comment]
Good luck with finding it. And feel free to reopen this issue if it turns out that this plugin is somehow involved :smile:
