### ISSUE TITLE
A question about type signature color

### ISSUE THREAD

**Issue by yen3** [MrcJkb/haskell-tools.nvim#29]
First, thank you for the great plugin. It contains lots of useful functions. I feel joy to write haskell programs with it.

I have a question. Is there any way to change the highlight of type signature? I try to find it but no idea.

<img width="884" alt="Screen Shot 2022-11-02 at 9 26 04 PM" src="https://user-images.githubusercontent.com/387292/199596099-b9e52b89-0279-4dec-b189-005dcfe31b0a.png">

Thank you for the help!

**Comment by MrcJkb** [comment]
Hi. Thanks for the nice feedback!

Neovim code lenses use the `LspCodeLens` highlight group.
So you could add something like this to your config:
```lua
vim.api.nvim_set_hl(0, 'LspCodeLens', { fg = '#5e5086', underline=false, })
```
where `fg` is the highlight of the code lens.

**Comment by MrcJkb** [comment]
Note: For some reason, it didn't work when I put it in my init.lua, but it did when I put it in the `on_attach` callback function.
I guess the hightlight group is cleared somewhere during startup.

**Comment by yen3** [comment]
Thank you for your prompt reply. It works now 👍 . Since I maintain [a customized theme](https://gitlab.com/yen3/dotfiles/-/blob/master/vim/lua/yen3/sunsetshiba.lua#L353), I did not add the setting in my init.lua. 

Thank you for your help again. Now it looks very helpful. :)

<img width="866" alt="Screen Shot 2022-11-03 at 6 10 19 AM" src="https://user-images.githubusercontent.com/387292/199651804-a3a62911-464c-4670-8eaf-fc27ed82bda8.png">
