### ISSUE TITLE
DAP error: `Error on launch: <file descriptor: 69>: hPutChar: resource vanished (Broken pipe)`

### ISSUE THREAD

**Issue by Per48edjes** [mrcjkb/haskell-tools.nvim#312]
### Neovim version (nvim -v)

v0.9.2

### Operating system/version

macOS Ventura 13.1

### Output of :checkhealth haskell-tools

```console
==============================================================================
haskell-tools: require("haskell-tools.health").check()

Checking for Lua dependencies ~
- OK [nvim-telescope/telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) installed.

Checking external dependencies ~
- OK haskell-language-server: found haskell-language-server version: 2.4.0.0 (GHC: 9.0.2) (PATH: /Users/rdayabhai/.local/share/nvim/mason/packages/haskell-language-server/lib/haskell-language-server-2.4.0.0/bin/haskell-language-server-wrapper)
- OK hoogle: found Hoogle 5.0.18.3, https://hoogle.haskell.org/
- WARNING       fast-tags: not found.
  Install [fast-tags](https://hackage.haskell.org/package/fast-tags) for extended capabilities.
  Optional, for generating tags as a `tagfunc` fallback.
  
- OK curl: found curl 7.85.0 (x86_64-apple-darwin22.0) libcurl/7.85.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0
- OK haskell-debug-adapter: found haskell-debug-adapter-0.0.39.0
- OK ghci-dap: found The Glorious Glasgow Haskell Compilation System, version 9.4.6

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.
```

### How to reproduce the issue

Start debugging session

### Expected behaviour

Trying to set up debugger with `haskell-tools.nvim`. I guess the expected behavior is what is demonstrated [here](https://user-images.githubusercontent.com/12857160/232348888-4fea5393-d624-417e-b994-6eb44113a3d9.gif)!

### Actual behaviour

When I attempt to open a debug session, the following error message is raised:

<img width="695" alt="image" src="https://github.com/mrcjkb/haskell-tools.nvim/assets/9625484/6ae3a753-41c4-4e64-aa21-38759d25e75f">

---

Note: I have my doubts that this is a `haskell-tools.nvim` issue, per se, but just raising in the event it is. If it's not, do let me know where I might start my debugging journey! 🙏🏽 

(I still need to develop a better understanding of how the necessary plugins work together to enable a rich debugging environment, but I do have the prerequisites all installed.)

### Log files

```console
https://gist.github.com/Per48edjes/bdb08c9612a6580ab2b5810bb8f5ce31
```

### The minimal config used to reproduce this issue.

```Lua
(Happy to 'guinea pig' this further if `haskell-tools.nvim` is indeed the cause!)
```

**Comment by Per48edjes** [comment]
(As I mentioned above, definitely feel free to close this if this is an issue not related to your plugin! Just looking to get a foothold as I try to get this debugger working.)

**Comment by mrcjkb** [comment]
Hey :wave: 

It looks like you're running into [this issue](https://github.com/phoityne/phoityne-vscode/issues/42), which appears to be a problem with `ghci-dap` (a dependency of `haskell-debug-adapter`.

**Comment by Per48edjes** [comment]
Yep, that was my impression...thanks, anyhow, @mrcjkb !
