### ISSUE TITLE
How to add import statements for variables on completion

### ISSUE THREAD

**Issue by Hsiwe** [mrcjkb/haskell-tools.nvim#358]
**Question**
Hi! Probably a dumb question but how do I add imports on auto-complete? I have nvim-cmp+cmp-nvim-lsp configured and I have correct suggestions, for example:
![image](https://github.com/mrcjkb/haskell-tools.nvim/assets/46127681/00167c2f-61dd-479d-9511-49fffa2f5413)

But when I confirm with `cmp.confirm()` it does not add any imports:
![image](https://github.com/mrcjkb/haskell-tools.nvim/assets/46127681/75a5b4e0-00b0-4591-9fdc-190f2427db33)

Am I missing some setting or is it not possible?
Thanks in advance!

**Comment by mrcjkb** [comment]
Hey 👋 

This plugin doesn't do anything completion related, besides registering the cmp-nvim-lsp client capabilities if it detects that it's installed. 

Auto import on confirm works for me ([here's my personal config](https://github.com/mrcjkb/nvim/blob/master/nvim/plugin/completion.lua), but I don't remember what config you might need to enable or disable.

If you can't get it to work, I would suggest asking there. 
If it works with other languages, but not Haskell, it could be that the version of haskell-language-server you're using [doesn't support it with your projects GHC version](https://haskell-language-server.readthedocs.io/en/stable/support/index.html).

**Comment by Hsiwe** [comment]
I was using GHC 9.8.1 + HLS 2.6.0.0, after switching to GHC 9.8.2 + HLS 2.7.0.0 the problem was solved, thanks!
