### ISSUE TITLE
Evaluate code snippets in comments

### ISSUE THREAD

**Issue by MrcJkb** [MrcJkb/haskell-tools.nvim#4]
https://haskell-language-server.readthedocs.io/en/latest/features.html#evaluation-code-snippets-in-comments

**Comment by Karthik-Dulam** [comment]
Cannot evaluate comments with the configuration in [Quick Setup](https://github.com/MrcJkb/haskell-tools.nvim#quick-setup) and [this demo](https://asciinema.org/a/TffryPrWpBkLnBK6dKXvOxd41). But Adding type signature works.
![image](https://user-images.githubusercontent.com/59601648/197363699-5975c044-2b2a-4303-acf2-18cd8f57e420.png)

**Comment by MrcJkb** [comment]
Hi. Thanks for reporting this, and thanks for the feedback :)
I was going to wait for a bit until I have implemented #7, and have used it myself for a while to be sure everything is stable, before posting it to reddit.

What's the output of `:LspInfo`?
Does it work for you add the quick setup to a [minimal neovim config](https://github.com/MrcJkb/nvim-minimal-packer)?

**Comment by Karthik-Dulam** [comment]
**I get the same result: Comment evaluation does not work but type signatures do.**

![image](https://user-images.githubusercontent.com/59601648/197391277-9b22ede3-6df3-419b-97d7-3f1b1a1fed0d.png)
```
 LspInfo
 Language client log: /home/.../.local/state/nvim/lsp.log
 Detected filetype:   haskell
 
 1 client(s) attached to this buffer: 
 
 Client: hls (id: 1, pid: nil, bufnr: [1])
 	filetypes:       haskell, lhaskell
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             haskell-language-server-wrapper --lsp
 	version:   haskell-language-server version: 1.8.0.0 (GHC: 9.4.2) (PATH: /home/.../.ghcup/hls/1.8.0.0/lib/haskell-language-server-1.8.0.0/bin/haskell-language-server-wrapper)
 
 Configured servers list: hls
```

**Comment by MrcJkb** [comment]
Ah, you are using ghc version 9.4.2, which [isn't fully supported by haskell-language-server yet](https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html).

At the moment, `hls` has full support for ghc versions 9.2.4 and below.

See also:
https://haskell-language-server.readthedocs.io/en/latest/support/plugin-support.html

**Comment by Karthik-Dulam** [comment]
Ah thank you for the info. Plugins like these make neovim very user-friendly.
