### ISSUE TITLE
Add support for opening documentation in browser in WSL

### ISSUE THREAD

**Issue by AntonVucinic** [mrcjkb/haskell-tools.nvim#402]
### Feature description

The issue we're facing is that we're using an executable (browser) that's running outside the WSL environment, but it needs the path to the file located within WSL. As far as I know, there isn't a reliable way of checking if the shell is running under WSL. Therefore, I propose adding a new configuration variable for the plugin: `wsl_distro`.
This would serve two purposes:
1. If set it would indicate to the plugin that the environment is indeed WSL and
2. it would be used to determine the path to files located inside WSL

This variable could be automatically set by the user's config script, as there are non-portable ways of detecting WSL.

The code changes would be minimal and it would allow the use of the user's default browser in Windows:
- the `browser_cmd` variable in the `open_browser` function should be set to 'explorer.exe'
- the url should be modified to reflect that the file is located on the WSL virtual drive `url = string.gsub(url, 'file://', 'file://///wsl.localhost/' .. vim.g.haskell_tools.wsl_distro, 1)`

I have already implemented the changes described above, and they appear to be working. However, I may have overlooked something, so a review would be helpful.

If this feature request is accepted, I am willing to implement the changes myself.

**Comment by mrcjkb** [comment]
Hey :wave: 

I'm afraid I don't have the capacity to add first-class support for Windows (a `wsl_distro` config option would communicate with users that there is first-class Windows support).
But I'd be fine with a config option, `tools.open_url?` of type `fun(url: string)`, which would override the `open_browser` function.

**Comment by AntonVucinic** [comment]
That might be an even better option. Do you want me to make a PR with that change?

**Comment by mrcjkb** [comment]
> That might be an even better option. Do you want me to make a PR with that change?

If you have time, that would be great 😄 🙏 
Otherwise, I might have some time for it tomorrow. 

In case you decide to open a PR: haskell-tools has two config modules: One user-facing one (where every field is optional/nullable) and one `config.internal` module where fields aren't optional.
There's also a `config.check` module with type validations.
