### ISSUE TITLE
What am I doing wrong? 

### ISSUE THREAD

**Issue by MangoIV** [MrcJkb/haskell-tools.nvim#63]
### Question

Hi, I cannot get it to work, my config looks like this: https://git.sr.ht/~mangoiv/dotfiles/tree/main/item/modules/home/devel/nvim/vimrc , I have all the required dependencies and `:LspInfo` just doesn't show the haskell-language-server. 
Additionally, nvim errs on startup when I try to set the repl options on ht. 
What am I doing wrong?

**Comment by MrcJkb** [comment]
It's probably the [`ht.setup = {...}`](https://git.sr.ht/~mangoiv/dotfiles/tree/main/item/modules/home/devel/nvim/vimrc#L228) call.

Instead of calling the setup function, you're replacing it with a lua table.
It should be:
```lua
ht.setup {
-- ...
}
```

Lua regularly sends shivers down my spine...

**Comment by MangoIV** [comment]
how stupid of me, thank you!

**Comment by MangoIV** [comment]
sorry, I don't know lua at all, I probably should learn it at some point. :D

**Comment by MrcJkb** [comment]
> how stupid of me, thank you!

Don't feel stupid. Lua is really nice for quick hacking, but you're never going to get anything robust out of it.
Stuff like that happens to me all the time (which is why I hope to set up detailed nix tests soon).

**Comment by MangoIV** [comment]
is there dhall2lua yet? :D 

Thank you for your help, I know my way forward now!
