### ISSUE TITLE
CI: Add stylua pre-commit hooks in accordance with .editorconfig

### ISSUE THREAD

**Issue by MrcJkb** [MrcJkb/haskell-tools.nvim#64]

**Comment by MangoIV** [comment]
You only have to change `stylua.enable = true` in the nix flake pre-commit attrset (careful, I made a typo there :D) 

The config I can't provide, as I don't know your preference in formatting for lua ;)

**Comment by MrcJkb** [comment]
Yes, I will have to look into tweaking the config myself (I don't agree with stylua's default indentation).

**Comment by MangoIV** [comment]
I think they have a way to configure that, I think I saw that when I quickly visited their github
