### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/haskell-tools.nvim#66]
@all-contributors
please add @MangoIV  for infra. 
please add @fabfianda  for doc.

**Comment by MrcJkb** [comment]
https://github.com/all-contributors
please add @MangoIV for infra.
please add @fabfianda for doc.

**Comment by MrcJkb** [comment]
@all-contributors
please add @MangoIV for infra.
please add @fabfianda for doc.

**Comment by MrcJkb** [comment]
@all-contributors
please add @fabfianda for doc.

**Comment by MrcJkb** [comment]
@all-contributors
please add @yen3 for code.

**Comment by mrcjkb** [comment]
@all-contributers
Please add @sebastianselander for code.

**Comment by mrcjkb** [comment]
@all-contributors
please add @sebastianselander for code.

**Comment by mrcjkb** [comment]
@all-contributers
please add @typesafety for code.

**Comment by mrcjkb** [comment]
@all-contributors
please add @typesafety for code.
