### ISSUE TITLE
fourmolu as formatting provider doesn't use `fourmolu.yaml` of project

### ISSUE THREAD

**Issue by MangoIV** [MrcJkb/haskell-tools.nvim#69]
### Neovim version (nvim -v)

v0.8.0

### Operating system/version

22.11.20221117.3a86856 (Raccoon)

### Output of `haskell-language-server --version`

1.8.0.0 (GHC: 9.2.4)

### How to reproduce the issue

use fourmolu as formatting provider

### Expected behaviour

fourmolu formats according to the fourmolu.yaml in the repository

### Actual behaviour

fourmolu uses default formatting

**Comment by MrcJkb** [comment]
Could you please add a fourmolu.yaml and a Haskell code snippet (if possible also a snippet with the expected formatting result) so I can reproduce this?

**Comment by MrcJkb** [comment]
I was able to reproduce it.
It'll probably be a few days before I can get back to this.

And I'll have to find out if it's an issue with haskell-tools.nvim or the hls-fourmolu-plugin.

If it works in another editor with the same language server executable, then it's probably a haskell-tools configuration issue.

**Comment by MrcJkb** [comment]
I found this lien in the hls log. It seems like hls is switching back to ormolu for some reason.
```console
 Debug | Configuration changed: Object (fromList [("haskell",Object (fromList [("formattingProvider",String "ormolu")]))])
```
[hls.log](https://github.com/MrcJkb/haskell-tools.nvim/files/10047867/hls.log)

**Comment by MrcJkb** [comment]
The issue was in the config. I forgot to wrap the `hls.haskell` configs in a `settings` table.
So you will have to adjust your config to:
```lua
ht.setup {
  hls = {
    settings = { -- This was missing 
      haskell = {
        formattingProvider = 'fourmolu', 
        -- ...
      }
    }
  }
}
```

**Comment by MangoIV** [comment]
thank you, that's really nice! thank you for fixing this so quickly, happy to be using this now :)

**Comment by MangoIV** [comment]
works like a charm!
