### ISSUE TITLE
Create rockspec so that luarocks can automatically map the plugin dependencies               

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/haskell-tools.nvim#75]
> NB: I see that you list several required packages: https://github.com/MrcJkb/haskell-tools.nvim#required would you mind adding a rockspec so that nixpkgs can automatically map the plugin dependencies ? I am trying to improve the neovim plugin dependency system via luarocks. See for instance https://github.com/lewis6991/gitsigns.nvim/blob/main/gitsigns.nvim-scm-1.rockspec

_Originally posted by @teto in https://github.com/MrcJkb/haskell-tools.nvim/issues/74

**Comment by MrcJkb** [comment]
Depends on https://github.com/neovim/nvim-lspconfig/pull/2307.

**Comment by teto** [comment]
of interest too https://github.com/nvim-telescope/telescope.nvim/pull/2276 (posting here to help me track all of them xD)

**Comment by MrcJkb** [comment]
Thanks for the update!
I will see if I can come up with an automated release/luarocks publish workflow to add to this PR, and hopefully also to telescope and plenary.
