### ISSUE TITLE
add option to auto-focus the builtin repl window

### ISSUE THREAD

**Issue by MrcJkb** [MrcJkb/haskell-tools.nvim#97]
In the mean time I'm using `repl.handler = 'builtin'` even if it's not ideal, as it doesn't automatically focus the repl, and I need to hit CTRL+W. 

_Originally posted by @gacallea in https://github.com/MrcJkb/haskell-tools.nvim/issues/92#issuecomment-1374780466_

**Comment by gacallea** [comment]
yay! :)
